-- HOOPMAP serverless backend for Supabase + Next.js.
-- Safe to run repeatedly in Supabase Dashboard > SQL Editor.

begin;

create schema if not exists extensions;
create schema if not exists gis;
create extension if not exists postgis with schema extensions;
set local search_path = public, extensions, gis;

create table if not exists public.profiles (
  id bigint generated by default as identity primary key,
  auth_user_id uuid not null unique references auth.users(id) on delete cascade,
  telegram_id bigint unique,
  username text not null default '',
  first_name text not null default '',
  last_name text not null default '',
  avatar_url text not null default '',
  role text not null default 'user' check (role in ('user', 'moderator', 'admin')),
  reputation integer not null default 0,
  map_home_lat numeric(5,2) check (map_home_lat between -90 and 90),
  map_home_lon numeric(6,2) check (map_home_lon between -180 and 180),
  map_home_consent_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles
  add column if not exists map_home_lat numeric(5,2)
    check (map_home_lat between -90 and 90),
  add column if not exists map_home_lon numeric(6,2)
    check (map_home_lon between -180 and 180),
  add column if not exists map_home_consent_at timestamptz;

create table if not exists public.courts (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 3 and 180),
  slug text not null unique,
  description text not null default '' check (char_length(description) <= 3000),
  address text not null check (char_length(address) between 5 and 300),
  city text not null,
  country text not null,
  latitude double precision not null check (latitude between -90 and 90),
  longitude double precision not null check (longitude between -180 and 180),
  location geography(point, 4326)
    generated always as (
      st_setsrid(st_makepoint(longitude, latitude), 4326)::geography
    ) stored,
  court_type text not null check (court_type in ('full', 'half', 'single_hoop', 'indoor', 'outdoor')),
  access_type text not null default 'free'
    check (access_type in ('free', 'restricted', 'paid', 'private')),
  surface text not null default 'other'
    check (surface in ('asphalt', 'rubber', 'concrete', 'parquet', 'other')),
  hoops_count smallint not null default 1 check (hoops_count between 1 and 20),
  has_lighting boolean not null default false,
  has_marking boolean not null default true,
  has_nets boolean not null default false,
  condition text not null default 'unknown'
    check (condition in ('excellent', 'good', 'fair', 'poor', 'unknown')),
  status text not null default 'pending'
    check (status in ('draft', 'pending', 'published', 'rejected', 'temporarily_closed', 'closed')),
  source text not null default '',
  source_id text not null default '',
  created_by bigint references public.profiles(id) on delete set null,
  verified_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists courts_unique_source
  on public.courts(source, source_id) where source <> '' and source_id <> '';
create index if not exists courts_location_gix on public.courts using gist(location);
create index if not exists courts_status_idx on public.courts(status);
create index if not exists courts_city_idx on public.courts(city);

create table if not exists public.court_photos (
  id bigint generated by default as identity primary key,
  court_id bigint not null references public.courts(id) on delete cascade,
  storage_path text not null unique,
  thumbnail_path text not null default '',
  uploaded_by bigint references public.profiles(id) on delete set null,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  created_at timestamptz not null default now()
);

create table if not exists public.court_reviews (
  id bigint generated by default as identity primary key,
  court_id bigint not null references public.courts(id) on delete cascade,
  user_id bigint not null references public.profiles(id) on delete cascade,
  rating smallint not null check (rating between 1 and 5),
  text text not null default '' check (char_length(text) <= 3000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (court_id, user_id)
);

create table if not exists public.court_reports (
  id bigint generated by default as identity primary key,
  court_id bigint not null references public.courts(id) on delete cascade,
  user_id bigint not null references public.profiles(id) on delete cascade,
  report_type text not null check (report_type in (
    'not_exists', 'closed', 'hoop_damaged', 'surface_damaged',
    'wrong_address', 'wrong_details', 'duplicate', 'other'
  )),
  description text not null default '' check (char_length(description) <= 3000),
  status text not null default 'open' check (status in ('open', 'resolved', 'rejected')),
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);

create table if not exists public.court_verifications (
  id bigint generated by default as identity primary key,
  court_id bigint not null references public.courts(id) on delete cascade,
  user_id bigint not null references public.profiles(id) on delete cascade,
  is_confirmed boolean not null default true,
  comment text not null default '' check (char_length(comment) <= 1000),
  created_at timestamptz not null default now()
);
create index if not exists court_verifications_lookup_idx
  on public.court_verifications(court_id, user_id, created_at desc);

create table if not exists public.favorite_courts (
  user_id bigint not null references public.profiles(id) on delete cascade,
  court_id bigint not null references public.courts(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, court_id)
);

create table if not exists public.games (
  id bigint generated by default as identity primary key,
  court_id bigint not null references public.courts(id) on delete restrict,
  creator_id bigint not null references public.profiles(id) on delete cascade,
  title text not null check (char_length(title) between 3 and 180),
  description text not null default '' check (char_length(description) <= 3000),
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  skill_level text not null default 'any'
    check (skill_level in ('any', 'beginner', 'intermediate', 'advanced')),
  max_players smallint not null default 10 check (max_players between 2 and 100),
  status text not null default 'scheduled'
    check (status in ('scheduled', 'in_progress', 'finished', 'cancelled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (ends_at > starts_at)
);
create index if not exists games_status_starts_idx on public.games(status, starts_at);

create table if not exists public.game_participants (
  game_id bigint not null references public.games(id) on delete cascade,
  user_id bigint not null references public.profiles(id) on delete cascade,
  status text not null default 'joined' check (status in ('joined', 'left')),
  joined_at timestamptz not null default now(),
  primary key (game_id, user_id)
);

create table if not exists public.api_rate_limits (
  scope_key text not null,
  bucket timestamptz not null,
  request_count integer not null default 1,
  primary key (scope_key, bucket)
);
alter table public.api_rate_limits enable row level security;

create or replace function public.set_updated_at()
returns trigger language plpgsql set search_path = '' as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at before update on public.profiles
for each row execute function public.set_updated_at();
drop trigger if exists courts_set_updated_at on public.courts;
create trigger courts_set_updated_at before update on public.courts
for each row execute function public.set_updated_at();
drop trigger if exists reviews_set_updated_at on public.court_reviews;
create trigger reviews_set_updated_at before update on public.court_reviews
for each row execute function public.set_updated_at();
drop trigger if exists games_set_updated_at on public.games;
create trigger games_set_updated_at before update on public.games
for each row execute function public.set_updated_at();

create or replace function public.current_profile_id()
returns bigint language sql stable security definer set search_path = ''
as $$ select id from public.profiles where auth_user_id = auth.uid() limit 1 $$;

create or replace function public.is_moderator()
returns boolean language sql stable security definer set search_path = ''
as $$
  select coalesce(
    (select role in ('moderator', 'admin') from public.profiles where auth_user_id = auth.uid()),
    false
  )
$$;

grant execute on function public.current_profile_id() to anon, authenticated;
grant execute on function public.is_moderator() to anon, authenticated;

create or replace function public.consume_rate_limit(
  target_key text,
  maximum_requests integer,
  window_seconds integer
)
returns boolean language plpgsql security definer set search_path = ''
as $$
declare
  current_bucket timestamptz;
  new_count integer;
begin
  if char_length(target_key) > 200 or maximum_requests not between 1 and 10000
    or window_seconds not between 1 and 86400 then
    raise exception 'Invalid rate limit';
  end if;
  current_bucket := to_timestamp(
    floor(extract(epoch from now()) / window_seconds) * window_seconds
  );
  insert into public.api_rate_limits(scope_key, bucket, request_count)
  values (target_key, current_bucket, 1)
  on conflict (scope_key, bucket) do update
    set request_count = public.api_rate_limits.request_count + 1
  returning request_count into new_count;
  delete from public.api_rate_limits where bucket < now() - interval '2 days';
  return new_count <= maximum_requests;
end;
$$;
revoke all on function public.consume_rate_limit(text, integer, integer) from public;
grant execute on function public.consume_rate_limit(text, integer, integer) to service_role;

alter table public.profiles enable row level security;
alter table public.courts enable row level security;
alter table public.court_photos enable row level security;
alter table public.court_reviews enable row level security;
alter table public.court_reports enable row level security;
alter table public.court_verifications enable row level security;
alter table public.favorite_courts enable row level security;
alter table public.games enable row level security;
alter table public.game_participants enable row level security;

drop policy if exists "profiles are public" on public.profiles;
create policy "profiles are public" on public.profiles for select using (true);

drop policy if exists "courts are visible" on public.courts;
create policy "courts are visible" on public.courts for select using (
  status = 'published' or created_by = public.current_profile_id() or public.is_moderator()
);
drop policy if exists "authenticated users create pending courts" on public.courts;
create policy "authenticated users create pending courts" on public.courts for insert
to authenticated with check (
  created_by = public.current_profile_id() and status = 'pending' and source = '' and source_id = ''
);
drop policy if exists "owners update pending courts" on public.courts;
create policy "owners update pending courts" on public.courts for update to authenticated
using (public.is_moderator() or (created_by = public.current_profile_id() and status in ('draft', 'pending')))
with check (public.is_moderator() or (created_by = public.current_profile_id() and status in ('draft', 'pending')));
drop policy if exists "owners delete pending courts" on public.courts;
create policy "owners delete pending courts" on public.courts for delete to authenticated
using (public.is_moderator() or (created_by = public.current_profile_id() and status in ('draft', 'pending')));

drop policy if exists "photos are visible" on public.court_photos;
create policy "photos are visible" on public.court_photos for select using (
  status = 'approved' or uploaded_by = public.current_profile_id() or public.is_moderator()
);
drop policy if exists "users add own photos" on public.court_photos;
create policy "users add own photos" on public.court_photos for insert to authenticated
with check (uploaded_by = public.current_profile_id() and status = 'pending');
drop policy if exists "moderators update photos" on public.court_photos;
create policy "moderators update photos" on public.court_photos for update to authenticated
using (public.is_moderator()) with check (public.is_moderator());

drop policy if exists "reviews are public" on public.court_reviews;
create policy "reviews are public" on public.court_reviews for select using (true);
drop policy if exists "users write own reviews" on public.court_reviews;
create policy "users write own reviews" on public.court_reviews for insert to authenticated
with check (user_id = public.current_profile_id());
drop policy if exists "users update own reviews" on public.court_reviews;
create policy "users update own reviews" on public.court_reviews for update to authenticated
using (user_id = public.current_profile_id()) with check (user_id = public.current_profile_id());

drop policy if exists "reports visible to author and moderators" on public.court_reports;
create policy "reports visible to author and moderators" on public.court_reports for select
using (user_id = public.current_profile_id() or public.is_moderator());
drop policy if exists "users create reports" on public.court_reports;
create policy "users create reports" on public.court_reports for insert to authenticated
with check (user_id = public.current_profile_id() and status = 'open');
drop policy if exists "moderators update reports" on public.court_reports;
create policy "moderators update reports" on public.court_reports for update to authenticated
using (public.is_moderator()) with check (public.is_moderator());

drop policy if exists "verifications are public" on public.court_verifications;
create policy "verifications are public" on public.court_verifications for select using (true);

drop policy if exists "users manage own favorites" on public.favorite_courts;
create policy "users manage own favorites" on public.favorite_courts for all to authenticated
using (user_id = public.current_profile_id()) with check (user_id = public.current_profile_id());

drop policy if exists "games are public" on public.games;
create policy "games are public" on public.games for select using (true);
drop policy if exists "creators update games" on public.games;
create policy "creators update games" on public.games for update to authenticated
using (creator_id = public.current_profile_id() or public.is_moderator())
with check (creator_id = public.current_profile_id() or public.is_moderator());

drop policy if exists "participants are public" on public.game_participants;
create policy "participants are public" on public.game_participants for select using (true);

-- Explicit grants prevent sensitive profile identifiers from being exposed by the Data API.
revoke all on table public.profiles from anon, authenticated;
grant select (id, username, first_name, last_name, avatar_url, role, reputation, created_at, updated_at)
  on public.profiles to anon, authenticated;
grant all on table public.profiles to service_role;

grant select on table
  public.courts, public.court_photos, public.court_reviews,
  public.court_verifications, public.favorite_courts, public.games, public.game_participants
to anon;
grant select, insert, update, delete on table
  public.courts, public.court_photos, public.court_reviews, public.court_reports,
  public.court_verifications, public.favorite_courts, public.games, public.game_participants
to authenticated;
grant usage, select on all sequences in schema public to authenticated, service_role;
grant all on table public.api_rate_limits to service_role;

create or replace function public.nearby_courts(
  lat double precision,
  lon double precision,
  radius_m integer default 5000
)
returns table (court_id bigint, distance_m integer)
language plpgsql stable security invoker set search_path = public, extensions, gis
as $$
begin
  if lat not between -90 and 90 or lon not between -180 and 180 then
    raise exception 'Coordinates are out of range';
  end if;
  if radius_m not between 1 and 100000 then
    raise exception 'Radius must be between 1 and 100000 meters';
  end if;
  return query
    select c.id, round(st_distance(
      c.location,
      st_setsrid(st_makepoint(lon, lat), 4326)::geography
    ))::integer
    from public.courts c
    where st_dwithin(
      c.location,
      st_setsrid(st_makepoint(lon, lat), 4326)::geography,
      radius_m
    )
    order by 2;
end;
$$;

create or replace function public.verify_court(
  target_court_id bigint,
  confirmed boolean default true,
  verification_comment text default ''
)
returns public.court_verifications
language plpgsql security definer set search_path = ''
as $$
declare
  profile_id bigint := public.current_profile_id();
  result public.court_verifications;
begin
  if profile_id is null then raise exception 'Authentication required'; end if;
  if char_length(verification_comment) > 1000 then raise exception 'Comment is too long'; end if;
  perform pg_advisory_xact_lock(target_court_id);
  if exists (
    select 1 from public.court_verifications
    where court_id = target_court_id and user_id = profile_id
      and created_at >= now() - interval '14 days'
  ) then
    raise exception 'Court was already verified recently';
  end if;
  insert into public.court_verifications(court_id, user_id, is_confirmed, comment)
  values (target_court_id, profile_id, confirmed, verification_comment)
  returning * into result;
  if confirmed then
    update public.courts set verified_at = now() where id = target_court_id;
  end if;
  return result;
end;
$$;

create or replace function public.create_game(
  target_court_id bigint,
  game_title text,
  game_description text,
  game_starts_at timestamptz,
  game_ends_at timestamptz,
  game_skill_level text,
  game_max_players integer
)
returns bigint language plpgsql security definer set search_path = ''
as $$
declare
  profile_id bigint := public.current_profile_id();
  game_id bigint;
begin
  if profile_id is null then raise exception 'Authentication required'; end if;
  if not exists (select 1 from public.courts where id = target_court_id and status = 'published') then
    raise exception 'Published court not found';
  end if;
  if char_length(game_title) not between 3 and 180 then raise exception 'Invalid title'; end if;
  if char_length(coalesce(game_description, '')) > 3000 then raise exception 'Description is too long'; end if;
  if game_ends_at <= game_starts_at then raise exception 'End must be after start'; end if;
  if game_skill_level not in ('any', 'beginner', 'intermediate', 'advanced') then
    raise exception 'Invalid skill level';
  end if;
  if game_max_players not between 2 and 100 then raise exception 'Invalid player limit'; end if;
  insert into public.games(
    court_id, creator_id, title, description, starts_at, ends_at, skill_level, max_players
  ) values (
    target_court_id, profile_id, game_title, coalesce(game_description, ''),
    game_starts_at, game_ends_at, game_skill_level, game_max_players
  ) returning id into game_id;
  insert into public.game_participants(game_id, user_id) values (game_id, profile_id);
  return game_id;
end;
$$;

create or replace function public.join_game(target_game_id bigint)
returns void language plpgsql security definer set search_path = ''
as $$
declare
  profile_id bigint := public.current_profile_id();
  selected_game public.games;
  joined_count integer;
begin
  if profile_id is null then raise exception 'Authentication required'; end if;
  select * into selected_game from public.games where id = target_game_id for update;
  if selected_game.id is null or selected_game.status <> 'scheduled' or selected_game.starts_at <= now() then
    raise exception 'Game cannot be joined';
  end if;
  select count(*) into joined_count from public.game_participants
    where game_id = target_game_id and status = 'joined';
  if joined_count >= selected_game.max_players then raise exception 'Game is full'; end if;
  if exists (
    select 1 from public.game_participants
    where game_id = target_game_id and user_id = profile_id and status = 'joined'
  ) then raise exception 'Already joined'; end if;
  insert into public.game_participants(game_id, user_id, status, joined_at)
  values (target_game_id, profile_id, 'joined', now())
  on conflict (game_id, user_id) do update set status = 'joined', joined_at = now();
end;
$$;

create or replace function public.leave_game(target_game_id bigint)
returns void language plpgsql security definer set search_path = ''
as $$
declare
  profile_id bigint := public.current_profile_id();
begin
  if profile_id is null then raise exception 'Authentication required'; end if;
  if exists (select 1 from public.games where id = target_game_id and creator_id = profile_id) then
    raise exception 'Creator must cancel the game';
  end if;
  update public.game_participants set status = 'left'
    where game_id = target_game_id and user_id = profile_id and status = 'joined';
  if not found then raise exception 'Not joined'; end if;
end;
$$;

revoke all on function public.verify_court(bigint, boolean, text) from public;
revoke all on function public.create_game(bigint, text, text, timestamptz, timestamptz, text, integer) from public;
revoke all on function public.join_game(bigint) from public;
revoke all on function public.leave_game(bigint) from public;
grant execute on function public.verify_court(bigint, boolean, text) to authenticated;
grant execute on function public.create_game(bigint, text, text, timestamptz, timestamptz, text, integer) to authenticated;
grant execute on function public.join_game(bigint) to authenticated;
grant execute on function public.leave_game(bigint) to authenticated;
grant execute on function public.nearby_courts(double precision, double precision, integer) to anon, authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'hoopmap-media', 'hoopmap-media', true, 10485760,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "court photos are publicly readable" on storage.objects;
create policy "court photos are publicly readable" on storage.objects for select
using (bucket_id = 'hoopmap-media');

commit;
