# Generated by Django 5.1.7 on 2026-07-22 12:51

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(db_index=True, max_length=120)),
                ('country', models.CharField(db_index=True, max_length=120)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, spatial_index=True, srid=4326)),
                ('court_type', models.CharField(choices=[('full', 'Полноценная'), ('half', 'Половина площадки'), ('single_hoop', 'Одно кольцо'), ('indoor', 'Крытая площадка'), ('outdoor', 'Уличная площадка')], max_length=20)),
                ('access_type', models.CharField(choices=[('free', 'Свободный'), ('restricted', 'Ограниченный'), ('paid', 'Платный'), ('private', 'Частный')], default='free', max_length=20)),
                ('surface', models.CharField(choices=[('asphalt', 'Асфальт'), ('rubber', 'Резина'), ('concrete', 'Бетон'), ('parquet', 'Паркет'), ('other', 'Другое')], default='other', max_length=20)),
                ('hoops_count', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(20)])),
                ('has_lighting', models.BooleanField(default=False)),
                ('has_marking', models.BooleanField(default=True)),
                ('has_nets', models.BooleanField(default=False)),
                ('condition', models.CharField(choices=[('excellent', 'Отличное'), ('good', 'Хорошее'), ('fair', 'Удовлетворительное'), ('poor', 'Плохое'), ('unknown', 'Неизвестно')], default='unknown', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На модерации'), ('published', 'Опубликована'), ('rejected', 'Отклонена'), ('temporarily_closed', 'Временно закрыта'), ('closed', 'Закрыта')], db_index=True, default='pending', max_length=24)),
                ('source', models.CharField(blank=True, max_length=80)),
                ('source_id', models.CharField(blank=True, max_length=160)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CourtPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='courts/originals/%Y/%m/')),
                ('thumbnail', models.ImageField(blank=True, upload_to='courts/thumbnails/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрена'), ('rejected', 'Отклонена')], db_index=True, default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='courts.court')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='court_photos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourtReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('not_exists', 'Площадки не существует'), ('closed', 'Площадка закрыта'), ('hoop_damaged', 'Повреждено кольцо'), ('surface_damaged', 'Повреждено покрытие'), ('wrong_address', 'Неверный адрес'), ('wrong_details', 'Неверные характеристики'), ('duplicate', 'Дубликат'), ('other', 'Другое')], max_length=24)),
                ('description', models.TextField(blank=True, max_length=3000)),
                ('status', models.CharField(choices=[('open', 'Открыта'), ('resolved', 'Решена'), ('rejected', 'Отклонена')], db_index=True, default='open', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='courts.court')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='court_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourtReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('text', models.TextField(blank=True, max_length=3000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='courts.court')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='court_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourtVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_confirmed', models.BooleanField(default=True)),
                ('comment', models.TextField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='courts.court')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='court_verifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteCourt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='courts.court')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_courts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='court',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('source', ''), _negated=True), models.Q(('source_id', ''), _negated=True)), fields=('source', 'source_id'), name='unique_nonempty_court_source'),
        ),
        migrations.AddConstraint(
            model_name='courtreview',
            constraint=models.UniqueConstraint(fields=('court', 'user'), name='unique_court_review'),
        ),
        migrations.AddConstraint(
            model_name='favoritecourt',
            constraint=models.UniqueConstraint(fields=('user', 'court'), name='unique_favorite_court'),
        ),
    ]
