# Generated by Django 5.1.7 on 2026-07-22 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True, max_length=3000)),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('ends_at', models.DateTimeField()),
                ('skill_level', models.CharField(choices=[('any', 'Любой'), ('beginner', 'Новичок'), ('intermediate', 'Средний'), ('advanced', 'Опытный')], default='any', max_length=20)),
                ('max_players', models.PositiveSmallIntegerField(default=10)),
                ('status', models.CharField(choices=[('scheduled', 'Запланирована'), ('in_progress', 'Проходит'), ('finished', 'Завершена'), ('cancelled', 'Отменена')], db_index=True, default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games', to='courts.court')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('starts_at',),
            },
        ),
        migrations.CreateModel(
            name='GameParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('joined', 'Участвует'), ('left', 'Вышел')], default='joined', max_length=16)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='games.gameevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_participations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='gameevent',
            index=models.Index(fields=['status', 'starts_at'], name='games_gamee_status_de5ef3_idx'),
        ),
        migrations.AddConstraint(
            model_name='gameparticipant',
            constraint=models.UniqueConstraint(fields=('game', 'user'), name='unique_game_participant'),
        ),
    ]
